package tests

fun main() {
    throw Exception("This is an exception")
}
